name: CI/CD workflow

env:
  SERVER_IP: "141.227.151.70"
  SERVER_USER: "root"

on:
  push:
    branches: [main]

jobs:
  check-tests-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    steps:
      - name: checkout le code
        uses: actions/checkout@v6
      - name: installer node.js
        uses: actions/setup-node@v6
        with:
          cache: 'npm'
          cache-dependency-path: ./server/package-lock.json
      - name: install dependencies
        run: npm ci --prefer-offline
      - name: vérifie le code
        run: npm run lint
      - name: vérifie les vulnerabilités des dépendances
        run: npm audit
      - name: éxécuter les tests
        run: npm run test:ci
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  check-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: checkout le code
        uses: actions/checkout@v6
      - name: installer node.js
        uses: actions/setup-node@v6
        with:
          cache: 'npm'
          cache-dependency-path: ./client/package-lock.json
      - name: install dependencies
        run: npm ci --prefer-offline
      - name: vérifie le code
        run: npm run lint
      - name: vérifie les vulnerabilités des dépendances
        run: npm audit

  build-frontend:
    needs: [check-frontend]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      - name: checkout le code
        uses: actions/checkout@v6
      - name: installer node.js
        uses: actions/setup-node@v6
        with:
          cache: 'npm'
          cache-dependency-path: ./client/package-lock.json
      - name: install dependencies
        run: npm ci --prefer-offline
      - name: vérifie le code
        run: npm run lint
      - name: build application front end
        run: npm run build
      - name: upload build
        uses: actions/upload-artifact@v6
        with:
          name: frontend-build
          path: ./client/dist
          retention-days: 30

  deploy:
    needs: [check-tests-backend,build-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: checkout le code
        uses: actions/checkout@v6
      - name: download build
        uses: actions/download-artifact@v6
        with:
          name: frontend-build
          path: ./dist
      - name: déployer sur le serveur
        run: |
          eval $(ssh-agent -s)
          ssh-add - <<< "${{ secrets.SSH_KEY_VPS }}"
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ env.SERVER_IP }} >> ~/.ssh/known_hosts
          scp -r ./server ${{ env.SERVER_USER }}@${{ env.SERVER_IP }}:/var/www
          scp -r ./dist ${{ env.SERVER_USER }}@${{ env.SERVER_IP }}:/var/www/dist
          ssh ${{ env.SERVER_USER }}@${{ env.SERVER_IP }} "cd /var/www/server && npm install --omit=dev"
          ssh ${{ env.SERVER_USER }}@${{ env.SERVER_IP }} "cd /var/www/server && pm2 startOrRestart ecosystem.config.js --env production && pm2 save"